<form action="Uzhnu\ChangeModule\Controller\Index\addProduct" method="POST">
    <strong><br><p>Новий продукт</p><br></strong>
    <p>Кількість:
        <input id="1" name="list[]" type="number" placeholder="Кількість"></p>
    <p>Назва:
        <input id="1" name="list[]" type="text" placeholder="Назва"></p>
    <input type="submit" value="Новий продукт">
</form>
<form action="Uzhnu\ChangeModule\Controller\Delete" method="POST">
    <strong><br><p>Видалити продукт</p><br></strong>
    <p>Id:<input id="1" name="id" type="number" placeholder="Id"></p>
    <input type="submit" value="Видалити">
</form>


