<?php
    use Uzhnu\ChangeModule\Block\Datasource;
    /** @var Datasource $block */

if(isset($_POST["list"])) {
    $i = 0;
    foreach ($_POST["list"] as $el){
        echo $el;
        $block->getListProduct()->get($i++)->chengInStock($el);
    }
} ?>


<form action="https://magento2.mgt/change" method="POST">
<ol>
    <?php foreach ($block->getListProduct() as $list):?>
        <li>
            <?= $list->getTitle() ?> - <?= $list->getCount() ?>
                <input id="<?= $list->getId() ?>" name="list[]" type="checkbox"
                        value="<?= $list->getStock()?>"
                    <?= ($list->getStock()) ? 'checked' : '' ?>
                       >
        </li>
    <?php endforeach;?>
</ol>
    <input type="submit" value="Обновити список">
</form>
<form action="https://magento2.mgt/change" method="POST">
<input id="111" name="id" type="number">
    <input type="submit" value="send">
</form>


